### ISSUE TITLE
Batch download does not recognize .mp4 as having a size

### ISSUE THREAD

**Issue by lazzarello** [beaufour/flickr-download#18]
Remember when Flickr launched short videos? Before Vine and Snapchat? No, me either but they did and it seems I uploaded some! This causes an exception due to this file type not having a size, or so it seems from the error output

```
Saving: lazzarello/5094118879.mp4
Traceback (most recent call last):
  File "/usr/local/bin/flickr_download", line 9, in <module>
    load_entry_point('flickr-download==0.2.15', 'console_scripts', 'flickr_download')()
  File "/usr/local/lib/python2.7/site-packages/flickr_download-0.2.15-py2.7.egg/flickr_download/flick_download.py", line 267, in main
    download_user_photos(args.download_user_photos, get_filename, args.quality)
  File "/usr/local/lib/python2.7/site-packages/flickr_download-0.2.15-py2.7.egg/flickr_download/flick_download.py", line 178, in download_user_photos
    download_list(user, username, get_filename, size_label)
  File "/usr/local/lib/python2.7/site-packages/flickr_download-0.2.15-py2.7.egg/flickr_download/flick_download.py", line 146, in download_list
    photo.save(fname, photo_size_label)
  File "/usr/local/lib/python2.7/site-packages/flickr_api/objects.py", line 1312, in save
    r = urllib2.urlopen(self.getPhotoFile(size_label))
  File "/usr/local/lib/python2.7/site-packages/flickr_api/objects.py", line 1290, in getPhotoFile
    raise FlickrError("The requested size is not available")
flickr_api.flickrerrors.FlickrError: The requested size is not available
```

**Comment by beaufour** [comment]
Feh. There's some other logic in there for videos:
https://github.com/beaufour/flickr-download/blob/master/flickr_download/flick_download.py#L132
maybe we just need to make sure that detection works for this type too? Or maybe it does detect it, but it's not `HD MP4` that is the magic size for this type of video. Neither API or my code is particularly pretty wrt this handling...

**Comment by beaufour** [comment]
@lazzarello do you have a (public) example of this, so I test and fix this?

**Comment by beaufour** [comment]
Seems like `Site MP4` works for these old videos – or at least for a couple of ones I've tested.

**Comment by beaufour** [comment]
This should be fixed on master

**Comment by lazzarello** [comment]
Would it be helpful if I found that .mp4? I don't have it off hand since I was doing a batch. I can run it again if needed.

**Comment by beaufour** [comment]
I searched from videos uploaded between 2008 and 2009 and found a few that I could test on :) I also added a `--download_photo` feature, so you can easily test just one photo (or video) which makes things a lot easier.

If you do happen to have that .mp4, please do test if I fixed it though

**Comment by emikelai** [comment]
Hi, I'm find this tool to be very useful, so first off, thanks! I hit an issue with downloading videos.

I ran this command (Nov 2022): 
    flickr_download -k <my key> -s <my secret> --download_user <my username> --user_auth --cach  api_cache --metadata_store

And it downloads  photos just fine (although it does timeout a lot. When the tool comes across a .mp4, this is the error that pops up:

ERROR:root:Flickr error saving photo: The requested size is not available

The comments above say it's fixed but I wanted to see if this was still an issue, since I'm facing it.

Thanks in advance!
~Mike

**Comment by beaufour** [comment]
I'm happy to hear that it's useful! Those darned videos. Is it by any
chance publicly available so I can see the error myself?

**Comment by emikelai** [comment]
Hi Beaufour, can you try this video? https://www.flickr.com/photos/selenamichael/35144138580/
I haven't tested downloading a single video yet as the tool is running and it's on a roll so I don't want to stop it. :)

**Comment by beaufour** [comment]
:) Perfect. That gives me something to debug. Thanks!

**Comment by beaufour** [comment]
Ok. It seems like Flickr has changed some things since 2016, and I've now also fixed the underlying API, so things should be good again on master. I just released a new version (v0.3.2) of the tool which should fix this.

**Comment by beaufour** [comment]
Yes, that should work. Let me know if it doesn't.

**Comment by emikelai** [comment]
Hi Beaufour,

Thanks, it worked (I ran a pip install flickr_download==0.3.2).

For one of the albums that had .mp4, the video files were downloaded successfully.

On another album, I hit an issue. I tried several times and it seems to stop at the same point. This is the printout in the terminal (in Pycharm) when there's an error. Does this give enough information (FYI it's an album with many iphone .mp4s which I believe are "live" photos. I never knew they were actually just .mp4s.

Thanks in advance,
Mike


Traceback (most recent call last):
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_api\objects.py", line 118, in __getattr__
    return self.__dict__[name]
           ~~~~~~~~~~~~~^^^^^^
KeyError: 'index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Scripts\flickr_download.exe\__main__.py", line 7, in <module>
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\flick_download.py", line 592, in main
    download_user(
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\flick_download.py", line 337, in download_user
    download_set(photoset.id, get_filename, size_label, skip_download, save_json)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\flick_download.py", line 125, in download_set
    download_list(
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\flick_download.py", line 174, in download_list
    do_download_photo(
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\flick_download.py", line 221, in do_download_photo
    fname = get_full_path(dirname, get_filename(pset, photo, suffix))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\filename_handlers.py", line 84, in title_increment
    extra = f"({photo.index})"
                ^^^^^^^^^^^
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_api\objects.py", line 120, in __getattr__
    raise AttributeError(
AttributeError: 'Photo' object has no attribute 'index'

**Comment by beaufour** [comment]
That's because I managed to introduce a bug in the last release 🤦 . Try 0.3.3

**Comment by emikelai** [comment]
Thanks @beaufour, 0.3.3 fixed most issues. For one album I am still seeing issues with downloading some videos. It's specific to this album but I believe it's because the videos are created/generated from either the LINE app or the WhatsApp app (these are videos that were taken on a phone and then I had transferred them to my computer and then uploaded to Flickr). I've made one such video public: https://www.flickr.com/photos/selenamichael/24170412187/ so you can try out any debugging.

The command I use to try and download this was the batch download where I would get this error:
"ERROR:root:IO error saving photo: HTTP Error 404: Not Found"

and when I try an individual download of the video I get:

flickr_download -k de061931c871cfe7ffcab56eb6475f91 -s <my secret> -t -i https://www.flickr.com/photos/selen
amichael/24170412187/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Scripts\flickr_download.exe\__main__.py", line 7, in <module>
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\flick_download.py", line 544, in main
    download_photo(
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\flick_download.py", line 304, in download_photo
    do_download_photo(".", None, photo, size_label, suffix, get_filename, skip_download, save_json)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\flick_download.py", line 224, in do_download_photo
    fname = get_full_path(dirname, get_filename(pset, photo, suffix))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\filename_handlers.py", line 91, in title_increment
    if not photo.title:
           ^^^^^^^^^^^
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_api\objects.py", line 116, in __getattr__
    self.load()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_api\objects.py", line 176, in load
    props = self.getInfo()
            ^^^^^^^^^^^^^^
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_api\reflection.py", line 256, in call
    r = method_call.call_api(method=flickr_method, **method_args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_api\method_call.py", line 150, in call_api
    raise FlickrAPIError(resp["code"], resp["message"])
flickr_api.flickrerrors.FlickrAPIError: 1 : Photo not found

**Comment by beaufour** [comment]
There are some videos the Flickr API simply doesn't return any video URLs for. It only returns web pages with a player. You can see for yourself in the API response here (put your own API key in):

https://www.flickr.com/services/rest/?method=flickr.photos.getSizes&photo_id=24170412187&format=rest&api_key=INSERT_API_KEY

If you look for the entries with `media=url` you can see that they all have a `source` that is a player, not a video file...

**Comment by emikelai** [comment]
Thanks @beaufour, I was able to individually download those videos with this issue. I really appreciate your time and support.

**Comment by beaufour** [comment]
No problem @emikelai ! Happy to hear.
